# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-25 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='drop_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Drop Site'),
        ),
    ]
