# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170328_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='submitted',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
