# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_cart_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
