# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-05 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180505_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='order_on_invoice',
        ),
    ]
