# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_merge_20180505_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order_on_invoice',
            field=models.IntegerField(default=0, help_text='Order this category will be printed on invoices. If this is a sub-category, this is the order printed within the parent category. 0 will be printed last. And sub-categories will only be sorted if the parent category has this value set'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL'),
        ),
    ]
