# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180508_2132'),
        ('shop', '0016_auto_20180505_1434'),
    ]

    operations = [
    ]
