# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-01 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20180901_1001'),
        ('shop', '0018_merge_20180811_1227'),
    ]

    operations = [
    ]
