# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-26 14:09
from __future__ import unicode_literals

import ffcsa.shop.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20191025_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorproductvariations',
            options={'verbose_name': 'Vendor Product Variation', 'verbose_name_plural': 'Vendor Product Variations'},
        ),
        migrations.AddField(
            model_name='productvariation',
            name='option1',
            field=ffcsa.shop.fields.OptionField(max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='option2',
            field=ffcsa.shop.fields.OptionField(max_length=50, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='type',
            field=models.IntegerField(choices=[(1, 'Size'), (2, 'Colour')], verbose_name='Type'),
        ),
    ]
