# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-28 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20191026_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
