# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models, IntegrityError


def set_variation_title(apps, schema_editor):
    ProductVariation = apps.get_model("shop", "ProductVariation")

    for pv in ProductVariation.objects.all():
        if pv.product.variations.count() > 1:
            pv.title = "{} - {}".format(pv.id, pv.product.title)
            pv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20191028_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='title',
            field=models.CharField(default='', help_text='Will default to Product.title', max_length=500, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.RunPython(set_variation_title),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set([('product', 'title')]),
        ),
    ]
