# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-29 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20191028_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='title',
            field=models.CharField(blank=True, help_text='defaults to the product title', max_length=500, verbose_name='Title'),
        ),
    ]
