# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields

def clear_carts(apps, scheme_editor):
    CartItem = apps.get_model("shop", "CartItem")
    CartItem.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20191029_1230'),
    ]

    operations = [
        migrations.RunPython(clear_carts),
        migrations.CreateModel(
            name='VendorCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
            ],
        ),
        migrations.AlterModelOptions(
            name='vendorproductvariation',
            options={'ordering': ('_order',), 'verbose_name': 'Vendor Product Variation', 'verbose_name_plural': 'Vendor Product Variations'},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='in_inventory',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='url',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='vendor_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='weekly_inventory',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.ProductVariation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorproductvariation',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='vendorcartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='shop.CartItem', verbose_name='Cart Item'),
        ),
        migrations.AddField(
            model_name='vendorcartitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Vendor', verbose_name='Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorcartitem',
            unique_together=set([('item', 'vendor')]),
        ),
    ]
