# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_cartitem_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
