# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20191105_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weekly_inventory',
            field=models.BooleanField(default=False, verbose_name='Weekly Inventory'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='weekly_inventory',
            field=models.BooleanField(default=False, verbose_name='Weekly Inventory'),
        ),
    ]
