# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-14 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_product_is_dairy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('title',)},
        ),
    ]
