# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20191114_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='extra',
            field=models.IntegerField(blank=True, help_text='The % extra to order. The extra ordered will be rounded to the nearest whole number.', null=True, verbose_name='% Extra'),
        ),
    ]
