# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_productvariation_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_instructions',
            field=models.TextField(blank=True, verbose_name='Shipping instructions'),
        ),
    ]
