# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-22 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_order_shipping_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
