# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='attending_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
