# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170427_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='attending_dinner',
            field=models.IntegerField(default=0),
        ),
    ]
