# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170826_2041'),
        ('shop', '0009_merge_20170729_0933'),
    ]

    operations = [
    ]
