# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_drop_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_detail_phone_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt. Phone'),
        ),
    ]
