# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_billing_detail_phone_2'),
        ('shop', '0012_merge_20171021_0846'),
    ]

    operations = [
    ]
