# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 04:32
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180508_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vendor_price',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vendor Price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_price',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vendor Price'),
        ),
    ]
