# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180811_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='weekly_inventory',
            field=models.BooleanField(default=True, verbose_name='Weekly Inventory'),
        ),
        migrations.AddField(
            model_name='product',
            name='weekly_inventory',
            field=models.BooleanField(default=True, verbose_name='Weekly Inventory'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='weekly_inventory',
            field=models.BooleanField(default=True, verbose_name='Weekly Inventory'),
        ),
    ]
