# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-11 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_merge_20180509_0717'),
        ('shop', '0017_auto_20180811_0938'),
    ]

    operations = [
    ]
