# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20190104_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allow_substitutions',
            field=models.BooleanField(default=True, verbose_name='Allow product substitutions'),
        ),
        migrations.AddField(
            model_name='order',
            name='no_plastic_bags',
            field=models.BooleanField(default=False, verbose_name='No Plastic Bags'),
        ),
    ]
