# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20190817_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_on_invoice',
            field=models.FloatField(blank=True, help_text="Order this product will be printed on invoices. If set, this will override the product's category order_on_invoice setting. This is a float number for more fine grained control. (ex. 2.1 will be sorted the same as if the product's parent category order_on_invoice was 2 & the product's category order_on_invoice was 1).", null=True),
        ),
    ]
