# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20191024_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_in_stock', models.IntegerField(blank=True, null=True, verbose_name='Number in stock')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendorproductvariations',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductVariation', verbose_name='variation'),
        ),
        migrations.AddField(
            model_name='vendorproductvariations',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Vendor', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='vendors',
            field=models.ManyToManyField(related_name='variations', through='shop.VendorProductVariations', to='shop.Vendor', verbose_name='Vendors'),
        ),
    ]
