# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20191026_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('my_field', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.product',),
        ),
    ]
