# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170328_2309'),
    ]

    operations = [
    ]
