# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170427_2125'),
        ('shop', '0004_remove_product_content_model'),
    ]

    operations = [
    ]
