# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170427_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
