# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_cart_submitted'),
        ('shop', '0007_merge_20170429_1300'),
    ]

    operations = [
    ]
