# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_drop_site'),
        ('shop', '0010_merge_20170826_2043'),
    ]

    operations = [
    ]
