# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-05 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_merge_20171126_1832'),
        ('shop', '0014_auto_20180505_0928'),
    ]

    operations = [
    ]
