# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0038_usersession'),
        ('shop', '0028_auto_20191026_0709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorProductVariations',
            new_name='VendorProductVariation',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='num_in_stock',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='option2',
        ),
        migrations.AlterField(
            model_name='productoption',
            name='type',
            field=models.IntegerField(verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorproductvariation',
            unique_together=set([('vendor', 'variation')]),
        ),
    ]
