# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-03 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0033_auto_20191102_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='title',
            new_name='_title',
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set([('product', '_title')]),
        ),
    ]
