# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-03 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20191103_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time'),
        ),
    ]
