# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20191105_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='auto_send_order',
            field=models.BooleanField(default=True, help_text='Automatically email order to vendor?'),
        ),
    ]
