# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_vendor_auto_send_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
