# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-13 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20191112_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_dairy',
            field=models.BooleanField(default=False, help_text='This is used to prevent unauthorized users from ordering dairy products'),
        ),
    ]
