# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 15:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0003_auto_20170409_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'.", regex='^\\+?(1-)?\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Contact Number'),
        ),
    ]
