# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drop_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Drop Site'),
        ),
    ]
