# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0005_profile_drop_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='CSA Start Date'),
        ),
    ]
