# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 01:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0006_profile_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'.", regex='^\\+?(1-)?\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Alternate Contact Number'),
        ),
    ]
