# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-12 00:16
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weekly_budget',
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_contribution',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Default Monthly Contribution'),
        ),
    ]
