# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-05 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0010_auto_20180505_0927'),
        ('ffcsa_core', '0010_auto_20180228_1226'),
    ]

    operations = [
    ]
