# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-24 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0011_auto_20180623_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ach_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('ACH', 'Bank Account'), ('CRYPTO', 'Crypto')], max_length=255, null=True),
        ),
    ]
