# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-25 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0012_auto_20180623_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid_signup_fee',
            field=models.BooleanField(default=False),
        ),
    ]
