# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-30 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0013_profile_paid_signup_fee'),
        ('ffcsa_core', '0011_merge_20180505_1432'),
    ]

    operations = [
    ]
