# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models

def migrate_ach_verified(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Profile = apps.get_model("ffcsa_core", "Profile")
    for profile in Profile.objects.all():
        if profile.ach_verified:
            profile.ach_status = 'VERIFIED'
        elif profile.payment_method == 'ACH':
            profile.ach_status = 'VERIFYING'
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0014_auto_20180811_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ach_status',
            field=models.CharField(choices=[('NEW', 'Unverified'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification Failed')], max_length=20, null=True),
        ),
        migrations.RunPython(migrate_ach_verified),
        migrations.RemoveField(
            model_name='profile',
            name='ach_verified',
        ),
        migrations.AlterField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, help_text='Use &lt;br/&gt; to enter a newline, and &lt;strong&gt;My Text&lt;/strong&gt; to make something bold.', verbose_name='Invoice Notes'),
        ),
    ]
