# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-11 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0015_auto_20180811_1138'),
        ('ffcsa_core', '0015_auto_20180629_1724'),
    ]

    operations = [
    ]
