# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0016_merge_20180811_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(null=True, verbose_name='Notes'),
        ),
    ]
