# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-03 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0018_auto_20190104_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='non_subscribing_member',
            field=models.BooleanField(default=False, help_text='Non-subscribing members are allowed to make payments to their ffcsa account w/o having a monthly subscription'),
        ),
    ]
