# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-03 16:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0019_profile_non_subscribing_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to maintain membership with the FFCSA for 12 months.If I need to change my monthly payment amount, I will notify the FFCSA admin and keep changes to a maximum of two times per year. I acknowledge there will be an additional $100 in my first months payment.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='product_agreement',
            field=models.FileField(default='', help_text="You can download the agreement <a href='/static/docs/Product Liability Agreement.pdf'>here</a>. All adult members in your household will need to sign the agreement", upload_to='', verbose_name='Signed Member Product Liability Agreement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'.", regex='^\\+?(1-)?\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Contact Number'),
        ),
    ]
