# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-03 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0020_auto_20190403_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_order',
            field=models.BooleanField(default=True, verbose_name='Has had dairy conversation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_agreement',
            field=models.BooleanField(default=False, help_text='If I need to change my monthly payment amount, I will notify the FFCSA admin and keep changes to a maximum of two times per year. I acknowledge there will be an additional $100 in my first months payment.', verbose_name='I agree to maintain membership with the FFCSA for 12 months.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='product_agreement',
            field=models.FileField(help_text="You can download the agreement <a target='_blank' href='/static/docs/Product Liability Agreement.pdf'>here</a>. All adult members in your household will need to sign the agreement", upload_to='uploads/member_docs/', verbose_name='Signed Member Product Liability Agreement'),
        ),
    ]
