# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0022_auto_20190403_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to make monthly payments in order to maintain my membership with the FFCSA for 12 months, with a minimium of $260 per month. If I need to change my monthly payment amount, I will notify the FFCSA admin and keep changes to a maximum of two times per year.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='product_agreement',
            field=models.FileField(help_text="Please <a target='_blank' href='/static/docs/Product Liability Agreement.pdf'>download this form</a> and have all adult members in your household sign. Then upload here.", upload_to='uploads/member_docs/', verbose_name='Liability Agreement Form'),
        ),
    ]
