# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0023_auto_20190408_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='product_agreement',
            field=models.FileField(blank=True, help_text="Please <a target='_blank' href='/static/docs/Product Liability Agreement.pdf'>download this form</a> and have all adult members in your household sign. Then upload here.", upload_to='uploads/member_docs/', verbose_name='Liability Agreement Form'),
        ),
    ]
