# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffcsa_core', '0026_auto_20190622_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Customer Notes'),
        ),
        migrations.RunSQL(
            "UPDATE ffcsa_core_profile SET notes = '<b>Best time to reach:</b><br/><b>Preferred communication method:</b><br/><b>Adults and children in family:</b><br/><b>How did you hear about us:</b><br/>'",
            reverse_sql=""
        )
    ]
