# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0027_profile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invoice_notes',
            field=models.TextField(blank=True, help_text='Use &lt;br/&gt; to enter a newline, and &lt;b&gt;My Text&lt;/b&gt; to make something bold.', verbose_name='Invoice Notes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notes',
            field=mezzanine.core.fields.RichTextField(blank=True, verbose_name='Customer Notes'),
        ),
    ]
