# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0031_auto_20190817_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_person_id',
            field=models.TextField(help_text='Google Person resource id', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_emails',
            field=models.BooleanField(default=True, help_text='Receive weekly newsletter and reminder emails.', verbose_name='Receive Weekly Emails'),
        ),
    ]
