# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20190817_1313'),
        ('pages', '0004_auto_20170411_0504'),
        ('ffcsa_core', '0033_auto_20190820_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('featured_image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
            ],
            options={
                'verbose_name': 'Recipe category',
                'verbose_name_plural': 'Recipe categories',
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffcsa_core.Recipe', verbose_name='Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(blank=True, through='ffcsa_core.RecipeProduct', to='shop.Product', verbose_name='Products'),
        ),
    ]
