# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20190817_1313'),
        ('ffcsa_core', '0035_auto_20190821_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.DiscountCode'),
        ),
    ]
