# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0036_profile_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.DiscountCode'),
        ),
    ]
