# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-13 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0038_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_order',
            new_name='can_order_dairy',
        ),
    ]
