# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0039_auto_20191113_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_delivery',
            field=models.BooleanField(default=False, help_text='Home delivery is available to select zip codes for a $5 fee. This fee is waived for all orders over $125', verbose_name='Home Delivery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to make monthly payments in order to maintain my membership with the FFCSA for 6 months, with a minimium of $172 per month.'),
        ),
    ]
