# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ffcsa_core', '0040_auto_20200320_1416'), ('ffcsa_core', '0041_auto_20200320_1611'), ('ffcsa_core', '0042_auto_20200320_1631'), ('ffcsa_core', '0043_auto_20200322_1002')]

    dependencies = [
        ('ffcsa_core', '0039_auto_20191113_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_delivery',
            field=models.BooleanField(default=False, help_text='Home delivery is available in select areas for a $5 fee. This fee is waived for all orders over $125.', verbose_name='Home Delivery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_agreement',
            field=models.BooleanField(default=False, verbose_name='I agree to make monthly payments in order to maintain my membership with the FFCSA for 6 months, with a minimium of $172 per month.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Special Delivery Notes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
    ]
