# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-20 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0040_auto_20200320_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Special Delivery Notes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_state',
            field=models.CharField(blank=True, default='Oregon', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zipcode'),
        ),
    ]
