# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-22 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0040_auto_20200320_1416_squashed_0043_auto_20200322_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_dairy_program',
            field=models.BooleanField(default=True, help_text='I would like to join the Raw Dairy program. I understand that I will be charged a $50 herd-share fee when making my first payment to gain access to raw dairy products.', verbose_name='Join Raw Dairy Program'),
        ),
    ]
