# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffcsa_core', '0042_auto_20200320_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='delivery_state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='delivery_zipcode',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='delivery_street',
            new_name='delivery_address'
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_delivery',
            field=models.BooleanField(default=False,
                                      help_text='Home delivery is available in select areas for a $5 fee. This fee is waived for all orders over $125.',
                                      verbose_name='Home Delivery'),
        ),
    ]
