# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0045_remove_profile_product_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropSiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_site_template_name', models.CharField(max_length=255, verbose_name='Drop Site Template Name')),
                ('last_hash_received', models.TextField(blank=True, null=True, verbose_name='Last Hash Received')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffcsa_core.Profile')),
            ],
        ),
    ]
