# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0046_dropsiteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropsiteinfo',
            name='last_hash_received',
        ),
        migrations.AddField(
            model_name='dropsiteinfo',
            name='last_version_received',
            field=models.TextField(blank=True, null=True, verbose_name='Last Version Received'),
        ),
    ]
