# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0047_auto_20200409_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
