# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ffcsa.core.models

_Address_Cache = {}


def cache_addresses(apps, schema_editor):
    Profile = apps.get_model("ffcsa_core", "Profile")

    for p in Profile.objects.filter(home_delivery=True):
        _Address_Cache[p.user_id] = p.delivery_address
        p.delivery_address = ''
        p.save()


def set_addresses(apps, schema_editor):
    for p in ffcsa.core.models.Profile.objects.filter(user_id__in=_Address_Cache.keys()):
        p.delivery_address = _Address_Cache[p.user_id]
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ffcsa_core', '0048_payment_is_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=165)),
                ('city', models.CharField(max_length=165)),
                ('state', models.CharField(max_length=165)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=165)),
            ],
        ),
        migrations.RunPython(cache_addresses),
        migrations.RemoveField(
            model_name='profile',
            name='delivery_address'
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=ffcsa.core.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='ffcsa_core.Address'),
        ),
        migrations.RunPython(set_addresses),
    ]
