# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ffcsa.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0049_auto_20200504_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='delivery_address',
            field=ffcsa.core.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ffcsa_core.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_delivery',
            field=models.BooleanField(default=False, help_text='Available in Eugene, Corvallis, and Springfield for a $5 fee. This fee is waived for all orders over $125.', verbose_name='Home Delivery'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['zip'], name='ffcsa_core__zip_3ef16e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['drop_site'], name='ffcsa_core__drop_si_f4f5fd_idx'),
        ),
    ]
