# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0050_auto_20200514_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ach_status',
            field=models.CharField(blank=True, choices=[('NEW', 'Unverified'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification Failed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CC', 'Credit Card'), ('ACH', 'Bank Account'), ('CRYPTO', 'Crypto')], max_length=255, null=True),
        ),
    ]
